// src/ui/angular/src/app/component/vegetable-form/vegetable-form.component.ts
import { Component, OnInit } from '@angular/core';
import { Vegetable } from '../../../../../../domain/model/Vegetable';
import { VegetablesService } from '../vegetables.service';

@Component({
  selector: 'app-vegetable-form',
  templateUrl: './vegetable-form.component.html',
  styleUrls: ['./vegetable-form.component.css'],
})
export class VegetableFormComponent implements OnInit {
  vegetable: Pick<Vegetable, 'name'> = { name: '' };

  private _vegetablesService: VegetablesService;

  constructor(vegetablesService: VegetablesService) {
    this._vegetablesService = vegetablesService;
  }

  ngOnInit(): void {}

  onSubmit() {
    this._vegetablesService.add(this.vegetable);
    this.vegetable = { name: '' };
  }
}

<form (ngSubmit)="onSubmit()" #heroForm="ngForm">
  <label>
    Name:
    <input type="text" [(ngModel)]="vegetable.name" name="name"/>
  </label>
  <button type="submit">Add</button>
</form>

// src/ui/solidjs/src/components/VegetableForm.tsx
import { Component } from "solid-js";
import { Vegetable } from "../../../../domain/model/Vegetable";
import { createStore } from "solid-js/store";
import { handleCommand } from "./repository";

type VegetableForm = Pick<Vegetable, "name">;

const VegetableForm: Component = () => {
  const [vegetable, setVegetable] = createStore<VegetableForm>({ name: "" });

  function onSubmit(e: Event) {
    e.preventDefault();
    handleCommand("AddVegetable", {
      name: vegetable.name,
    });
    setVegetable({ name: "" } as Vegetable);
  }

  function onChange(e: Event) {
    setVegetable({
      name: (e.currentTarget as HTMLInputElement).value,
    } as Vegetable);
  }

  return (
    <form onSubmit={onSubmit}>
      <label>
        Name:
        <input type="text" value={vegetable.name} onChange={onChange} />
      </label>
      <button type="submit">Add</button>
    </form>
  );
};

export default VegetableForm;
