// src/ui/solidjs/src/components/VegetableItem.tsx
import { Component } from "solid-js";
import { Vegetable, VegetableId } from "../../../../domain/model/Vegetable";
import { handleCommand } from "../hexagone";

type VegetableComponentType = { vegetable: Vegetable };

const VegetableItem: Component<VegetableComponentType> = (
  props: VegetableComponentType
) => {
  function remove(v: Vegetable) {
    handleCommand<VegetableId>("RemoveVegetable", v.id);
  }

  const { vegetable } = props;
  return (
    <div>
      {vegetable.id.id} - {vegetable.name}
      <button onClick={() => remove(props.vegetable)}>X</button>
    </div>
  );
};

export default VegetableItem;

// src/ui/react/src/components/VegetableItem.tsx
import { Vegetable, VegetableId } from "../../../../domain/model/Vegetable";
import { handleCommand } from "../hexagone";

type VegetableItemParams = { vegetable: Vegetable };
export default function VegetableItem(props: VegetableItemParams) {
  const { vegetable } = props;

  function remove(v: Vegetable) {
    handleCommand<VegetableId>("RemoveVegetable", v.id);
  }

  return (
    <>
      {vegetable.id.id} - {vegetable.name}
      <button onClick={() => remove(vegetable)}>X</button>
    </>
  );
}
