// src/ui/solidjs/src/components/Vegetables.tsx
import { Component, For } from "solid-js";
import VegetableItem from "./VegetableItem";
import { Vegetable } from "../../../../domain/model/Vegetable";
import { createVegetableResource } from "./vegetableResource";
import VegetableForm from "./VegetableForm";

const Vegetables: Component = () => {
  const { vegetables } = createVegetableResource();
  return (
    <>
      <VegetableForm></VegetableForm>
      <ul>
        <For each={vegetables()}>
          {(vegetable: Vegetable) => (
            <li>
              <VegetableItem vegetable={vegetable} />
            </li>
          )}
        </For>
      </ul>
    </>
  );
};

export default Vegetables;

// src/ui/react/src/components/Vegetables.tsx
import VegetableForm from "./VegetableForm";
import VegetableItem from "./VegetableItem";
import useVegetableList from "./useVegetableList";

export default function Vegetables() {
  const list = useVegetableList();

  return (
    <>
      <VegetableForm></VegetableForm>
      <ul>
        {list.map((v) => (
          <li key={v.id.id}>
            <VegetableItem vegetable={v}></VegetableItem>
          </li>
        ))}
      </ul>
    </>
  );
}
